import { useState, useMemo } from 'react';
import { post } from '../App';
import { Select } from '../components/Select';
import type { LibraryImage } from '../types/messages';

interface Props {
  images: LibraryImage[];
  projectRoot: string;
  hasImagesFolder?: boolean;
}

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

export function Library({ images, projectRoot, hasImagesFolder = true }: Props) {
  const [selectedPath, setSelectedPath] = useState<string | null>(null);
  const [filterFolder, setFilterFolder] = useState<string>('all');
  const [viewMode, setViewMode] = useState<'grid' | 'list'>('grid');

  // Extract unique folders
  const folders = useMemo(() => {
    const set = new Set(images.map(i => i.folder));
    return ['all', ...Array.from(set).sort()];
  }, [images]);

  // Filter images
  const filtered = useMemo(() => {
    if (filterFolder === 'all') return images;
    return images.filter(i => i.folder === filterFolder);
  }, [images, filterFolder]);

  const selected = images.find(i => i.path === selectedPath);

  return (
    <div className="mx-auto w-full max-w-5xl">
      {/* Header */}
      <div className="mb-6 flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold">Library</h1>
          <p className="mt-1 text-sm text-[var(--text-secondary)]">
            Images in your project — generated by Ava or added manually
          </p>
        </div>
        <button
          onClick={() => post({ type: 'load_library' })}
          className="rounded-lg border border-[var(--border)] px-3 py-1.5 text-xs font-medium text-[var(--text-secondary)] hover:text-[var(--text-primary)] transition"
        >
          Scan
        </button>
      </div>

      {/* Toolbar */}
      <div className="mb-4 flex items-center gap-3">
        {/* Folder filter */}
        <div className="w-52">
          <Select
            value={filterFolder}
            onChange={setFilterFolder}
            options={folders.map(f => ({
              value: f,
              label: f === 'all' ? `All folders (${images.length})` : `${f} (${images.filter(i => i.folder === f).length})`,
            }))}
          />
        </div>

        {/* View toggle */}
        <div className="ml-auto flex rounded-lg border border-[var(--border)] overflow-hidden">
          <button
            onClick={() => setViewMode('grid')}
            className={`px-2.5 py-1.5 text-xs ${viewMode === 'grid' ? 'bg-[var(--accent)] text-white' : 'text-[var(--text-secondary)]'}`}
          >
            <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M4 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2V6zM14 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V6zM4 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2v-2zM14 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z" />
            </svg>
          </button>
          <button
            onClick={() => setViewMode('list')}
            className={`px-2.5 py-1.5 text-xs ${viewMode === 'list' ? 'bg-[var(--accent)] text-white' : 'text-[var(--text-secondary)]'}`}
          >
            <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M4 6h16M4 12h16M4 18h16" />
            </svg>
          </button>
        </div>
      </div>

      {/* Empty state */}
      {images.length === 0 && (
        <div className="rounded-2xl border border-[var(--border)] bg-[var(--bg-card)] p-12 text-center">
          <div className="text-4xl mb-3">{hasImagesFolder ? '🎨' : '📁'}</div>
          <p className="text-sm font-medium text-[var(--text-primary)]">
            {hasImagesFolder ? 'No images found' : 'No images/ folder found'}
          </p>
          <p className="mt-1 text-xs text-[var(--text-secondary)]">
            {hasImagesFolder
              ? 'Ask Ava to generate an image and it will appear here.'
              : 'This project doesn\'t have an images/ folder yet. Ask Ava to generate an image and she\'ll create it for you.'}
          </p>
          <p className="mt-3 text-xs text-[var(--text-muted)]">
            Scans: images/ folder and all subfolders
          </p>
        </div>
      )}

      {/* Grid view */}
      {filtered.length > 0 && viewMode === 'grid' && (
        <div className="grid grid-cols-3 sm:grid-cols-4 lg:grid-cols-5 gap-3">
          {filtered.map(img => (
            <button
              key={img.path}
              onClick={() => setSelectedPath(selectedPath === img.path ? null : img.path)}
              className={`group relative aspect-square rounded-xl overflow-hidden border transition hover:border-[var(--accent)]/50 ${
                selectedPath === img.path ? 'border-[var(--accent)] ring-2 ring-[var(--accent)]/30' : 'border-[var(--border)]'
              }`}
            >
              <img
                src={`vscode-resource:${projectRoot}/${img.path}`}
                alt={img.name}
                className="w-full h-full object-cover"
                loading="lazy"
              />
              <div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/70 to-transparent p-2 opacity-0 group-hover:opacity-100 transition">
                <p className="text-[10px] text-white font-medium truncate">{img.name}</p>
                <p className="text-[9px] text-white/60">{formatSize(img.size)}</p>
              </div>
            </button>
          ))}
        </div>
      )}

      {/* List view */}
      {filtered.length > 0 && viewMode === 'list' && (
        <div className="rounded-xl border border-[var(--border)] bg-[var(--bg-card)] overflow-hidden">
          {filtered.map((img, i) => (
            <button
              key={img.path}
              onClick={() => setSelectedPath(selectedPath === img.path ? null : img.path)}
              className={`w-full flex items-center gap-3 px-4 py-2.5 text-left transition hover:bg-[var(--bg-hover)] ${
                i > 0 ? 'border-t border-[var(--border)]' : ''
              } ${selectedPath === img.path ? 'bg-[var(--accent)]/5' : ''}`}
            >
              <img
                src={`vscode-resource:${projectRoot}/${img.path}`}
                alt={img.name}
                className="w-10 h-10 rounded-lg object-cover border border-[var(--border)]"
                loading="lazy"
              />
              <div className="flex-1 min-w-0">
                <p className="text-sm font-medium text-[var(--text-primary)] truncate">{img.name}</p>
                <p className="text-[11px] text-[var(--text-muted)]">{img.folder}</p>
              </div>
              <div className="text-right shrink-0">
                <p className="text-[11px] text-[var(--text-secondary)]">{formatSize(img.size)}</p>
                {img.dimensions && <p className="text-[10px] text-[var(--text-muted)]">{img.dimensions}</p>}
              </div>
            </button>
          ))}
        </div>
      )}

      {/* Selected image detail */}
      {selected && (
        <div className="mt-4 rounded-xl border border-[var(--border)] bg-[var(--bg-card)] p-4">
          <div className="flex gap-4">
            <img
              src={`vscode-resource:${projectRoot}/${selected.path}`}
              alt={selected.name}
              className="w-48 h-48 rounded-lg object-contain bg-black/20 border border-[var(--border)]"
            />
            <div className="flex-1">
              <h3 className="text-sm font-bold text-[var(--text-primary)]">{selected.name}</h3>
              <p className="text-xs text-[var(--text-muted)] mt-1">{selected.path}</p>

              <div className="mt-3 space-y-1.5">
                <div className="flex justify-between text-xs">
                  <span className="text-[var(--text-secondary)]">Size</span>
                  <span className="text-[var(--text-primary)]">{formatSize(selected.size)}</span>
                </div>
                {selected.dimensions && (
                  <div className="flex justify-between text-xs">
                    <span className="text-[var(--text-secondary)]">Dimensions</span>
                    <span className="text-[var(--text-primary)]">{selected.dimensions}</span>
                  </div>
                )}
                <div className="flex justify-between text-xs">
                  <span className="text-[var(--text-secondary)]">Modified</span>
                  <span className="text-[var(--text-primary)]">{new Date(selected.modified).toLocaleDateString()}</span>
                </div>
              </div>

              <div className="mt-4 flex gap-2">
                <button
                  onClick={() => post({ type: 'open_library_image', path: selected.path })}
                  className="flex-1 py-2 rounded-lg text-xs font-medium bg-[var(--accent)] text-white hover:opacity-90 transition"
                >
                  Open in Editor
                </button>
                <button
                  onClick={() => {
                    navigator.clipboard.writeText(selected.path);
                  }}
                  className="px-3 py-2 rounded-lg text-xs font-medium border border-[var(--border)] text-[var(--text-secondary)] hover:text-[var(--text-primary)] transition"
                >
                  Copy Path
                </button>
                <button
                  onClick={() => {
                    post({ type: 'delete_library_image', path: selected.path });
                    setSelectedPath(null);
                  }}
                  className="px-3 py-2 rounded-lg text-xs font-medium border border-[var(--border)] text-[var(--text-secondary)] hover:text-red-400 hover:border-red-400/50 transition"
                >
                  Delete
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Footer */}
      {images.length > 0 && (
        <p className="mt-4 text-center text-[11px] text-[var(--text-muted)]">
          {images.length} image{images.length !== 1 ? 's' : ''} across {folders.length - 1} folder{folders.length - 1 !== 1 ? 's' : ''}
        </p>
      )}
    </div>
  );
}
