import type { DocPage } from '../types.js';

// Section 2 — Core concepts. Useful to everyone.

export const CONCEPT_PAGES: DocPage[] = [
  {
    id: 'models.routing',
    title: 'Routing — how Ava picks models',
    audience: ['both'],
    surfaces: ['web', 'ext', 'ide'],
    order: 10,
    section: 'models',
    body: [
      { type: 'paragraph', text: 'Ava is a thinking system, not a model menu. You pick one of three orchestration strategies — Maestro, Supernova, or Aurora — and Ava routes each subtask to the model best suited for it. Coordinator-tier reasoning where it matters; flash-tier specialists for high-volume work. Same persona pipeline runs on all three; what changes is the underlying fleet.' },

      { type: 'heading', level: 3, text: 'Maestro' },
      { type: 'paragraph', text: 'One conductor handles every persona. Qwen 3.6 Plus drives the full pipeline — Scout reads, Architect plans, Builder edits, Verifier checks. Same model, same context window, no handoff cost. Production-tuned, proven across months of operator workloads, default for everyone. Live on every plan.' },

      { type: 'heading', level: 3, text: 'Supernova' },
      { type: 'paragraph', text: 'Polyglot ensemble. DeepSeek V4 Pro coordinates (1.6T total parameters / 49B active, 1M context, frontier tool-call reliability) and dispatches to specialists per task. Builder runs on Qwen 3.6 Plus — Terminal-Bench leader, production-tested. V4 Flash handles mid-tier review and verification work. Qwen 3.5 Omni Plus takes over when there is vision input. Light specialists (Scout, Verifier, Sequencer, Challenger) run on Qwen 3.5 Flash to keep the bulk of token volume cheap.' },

      { type: 'heading', level: 3, text: 'Aurora' },
      { type: 'paragraph', text: 'European AI stack — sovereign by design. Mistral Large 3 coordinates (sparse MoE, 41B active / 675B total) and handles the depth-heavy specialists: Researcher, Challenger, CVE Researcher, Ideator. Mistral Small 4 covers Architect, Builder, Verifier, Sequencer, Tutor — Devstral lineage plus Pixtral vision in one model at flash-tier pricing. Apache-2.0 open weights. Never leaves EU infrastructure. Built for GDPR-strict deployments, public-sector and healthcare buyers, sovereignty-mandated workloads.' },

      { type: 'heading', level: 3, text: 'Why orchestration?' },
      { type: 'paragraph', text: 'Routing each subtask to the right specialist costs less than running every step on a frontier model — and produces better results, because each model is used for what it is best at. Coordinator tokens get spent on reasoning and planning; build-tier tokens flow to flash-tier models. Cost stays predictable, quality stays high, and you do not need to know which model to pick — Ava picks for each step.' },

      { type: 'callout', variant: 'note', text: 'All three modes are universally available — on platform credits and on your own keys. BYOK adds the option to bypass orchestration and drive a single model directly when you want that level of control.' },

      { type: 'heading', level: 3, text: 'Switching modes' },
      { type: 'paragraph', text: 'The model picker at the top of the chat panel lists the three orchestrated modes first, then any individual models you have keys for. Switch mid-conversation — memory carries across, the active task continues on the new fleet on the next turn.' },
    ],
  },
  {
    id: 'credits.overview',
    title: 'Ava Credits — how billing works',
    audience: ['both'],
    surfaces: ['web', 'ext', 'ide'],
    order: 10,
    section: 'credits',
    body: [
      { type: 'paragraph', text: 'Ava bills in credits, not raw tokens. One credit covers one unit of work — a chat turn, a persona spawn, an image generation. Decoupling from token-level metering means you do not need to know which model is running to know what an action will cost. The same chat_turn costs the same whether Maestro routes it to Qwen 3.6 Plus or Supernova routes it to V4 Pro.' },

      { type: 'heading', level: 3, text: 'Plans' },
      { type: 'paragraph', text: 'Every plan has access to every feature — model access, Creative Studio, all six modes, the full persona orchestration. Higher tiers buy more credits and a higher rate-limit ceiling, not unlocked features.' },
      { type: 'list', ordered: false, items: [
        'Free — $0/month. 300 credits. 20 requests/minute rate limit. No card required.',
        'Pro — $19/month. 5,000 credits. 60 requests/minute.',
        'Ultra — $39/month. 10,000 credits. 120 requests/minute.',
        'Enterprise — $79/month. 20,000 credits. 200 requests/minute.',
      ]},
      { type: 'callout', variant: 'note', text: 'Unused credits roll over while your subscription is active — there is no forced clawback. Top-ups stack on the subscription pool: 750 credits for $3, 2,000 for $8, 4,000 for $15.' },

      { type: 'heading', level: 3, text: 'What things cost' },
      { type: 'paragraph', text: 'Per-action cost table — what gets deducted from your credit pool when each action runs. Cache hits discount the charge by 70% (or 50% on output-heavy models like DeepSeek V4 Pro).' },
      { type: 'list', ordered: false, items: [
        'Chat turn — 2 credits. A single back-and-forth in any mode.',
        'Light call — 1 credit. Intent gate, classification, single-shot read.',
        'Heavy persona — 3 credits. Architect, Researcher, CVE Researcher, Ideator (depth ≥ 4).',
        'Light persona — 1 credit. Scout, Verifier, Sequencer, Challenger (depth ≤ 2).',
        'Orchestration — 10 credits. Full persona pipeline spawn (Conductor + multi-persona task).',
        'Image generation — 12 credits. Hailuo image-01 via Creative Studio.',
        'Video generation — 150 credits. Hailuo 02 Pro 1080p 6s clip.',
        'Voice generation — 10 credits. Speech 2.8 HD synthesis.',
        'Music generation — 50 credits. MiniMax Music 2.5/2.6.',
        'Background removal — 2 credits.',
      ]},

      { type: 'heading', level: 3, text: 'Per-model multipliers' },
      { type: 'paragraph', text: 'Heavier models multiply the action cost so credits track real spend instead of a flat bracket. Calibrated for ~55% net margin.' },
      { type: 'list', ordered: false, items: [
        '0.6× — Mistral Small 4 (Aurora\'s specialist seat). Sub-1× because Mistral Small 4 is cheaper than the Qwen 3.6 Plus anchor.',
        '1.0× — Qwen 3.5 Flash, Qwen Omni Flash, DeepSeek V4 Flash, MiniMax. Base rate.',
        '1.2× — Qwen 3.5 Plus, Qwen 3.5 Omni Plus.',
        '1.4× — Mistral Large 3 (Aurora coordinator). About par with the Qwen 3.6 Plus anchor.',
        '1.5× — Qwen 3.6 Plus (Maestro coordinator).',
        '6.0× — DeepSeek V4 Pro (Supernova coordinator + heavy specialists). Recalibrated from 5.0× to restore margin parity at the published V4 Pro rate.',
      ]},
      { type: 'callout', variant: 'note', text: 'Anthropic models (Claude Opus / Sonnet / Haiku) skip credit billing entirely — they are BYOK only and you pay Anthropic directly. Same for any other BYOK provider when used with your own key.' },

      { type: 'heading', level: 3, text: 'BYOK and credits' },
      { type: 'paragraph', text: 'Bring-your-own-key requests bypass platform infrastructure entirely — the call goes direct from Ava to the provider, you pay the provider, no credits are consumed. The only exception is when a BYOK session spawns a managed-tier persona for a sub-task; the credit deduction still applies because Ava\'s orchestration surface is being used.' },

      { type: 'heading', level: 3, text: 'Where to check your balance' },
      { type: 'list', ordered: false, items: [
        'Extension — Settings → Account, or the credit pill in the chat header.',
        'IDE — Account dashboard tile shows current balance and burn rate.',
        'Web — ava-supernova.com/dashboard shows balance, history, and renewal date.',
      ]},
      { type: 'callout', variant: 'tip', text: 'Local-first: Ava works without an account on the Custom Model card (Ollama, LM Studio, vLLM, or any OpenAI-compatible endpoint). No credits, no platform tokens — your model, your machine, your bill of zero.' },
    ],
  },
  {
    id: 'concepts.modes',
    title: 'The six modes',
    audience: ['both'],
    surfaces: ['web', 'ext', 'ide'],
    order: 10,
    section: 'concepts',
    body: [
      { type: 'paragraph', text: 'Modes change how Ava thinks, not what she can do. The same agent, the same memory, but a different mindset and a different team of specialists behind her. Type a two-character prefix to switch, or pick from the mode selector.' },
      { type: 'facts', kind: 'modes' },
      { type: 'heading', level: 3, text: 'When to use which' },
      { type: 'list', ordered: false, items: [
        'Work (>>) — you know what you want and you want it built. Full tool access. For complex multi-file work the persona team runs automatically.',
        'Plan (::) — you want a considered approach before any code changes. Read-only. You get a plan you can approve, edit, or discard.',
        'Chat (..) — you want to talk. About life, about an idea, about nothing in particular. She has memory, news, weather, and journal — and no personas.',
        'Teach (??) — you want to learn. Curriculum, lessons, quizzes, spaced repetition. Free on every plan forever.',
        'Security (!!) — you want the whole project audited. Five specialists systematically check OWASP categories and CVEs, then produce a severity-sorted report.',
        'Brainstorm (**) — you want ideas. Grounded in your context, challenged before they leave the room, refined into next steps.',
      ]},
      { type: 'callout', variant: 'tip', text: 'You can switch modes mid-conversation. Memory carries across. The specialists do not.' },
    ],
  },
  {
    id: 'concepts.memory',
    title: 'Memory — how Ava remembers you',
    audience: ['both'],
    surfaces: ['web', 'ext', 'ide'],
    order: 20,
    section: 'concepts',
    body: [
      { type: 'paragraph', text: 'Ava has a persistent memory that survives across conversations, across projects, and across machines if you enable sync. It is not a chat log. It is a structured, searchable understanding of who you are, what you like, and what you have decided.' },
      { type: 'heading', level: 3, text: 'Five layers' },
      { type: 'list', ordered: true, items: [
        'Extract — key facts captured from every message in real time.',
        'Reflect — deeper analysis runs at the end of meaningful sessions. Patterns, themes, contradictions.',
        'Accumulate — corrections and preferences compound over weeks and months.',
        'Analyse — the graph engine links related memories and flags contradictions when new information conflicts with old.',
        'Consolidate — similar memories merge; stale ones prune. Memory gets sharper over time, not noisier.',
      ]},
      { type: 'heading', level: 3, text: 'Recall' },
      { type: 'paragraph', text: 'When you ask a question, Ava searches memory by meaning (semantic search), not keywords. Mode-specific filters run alongside — Chat mode pulls personal context, Work mode pulls project decisions and code patterns.' },
      { type: 'callout', variant: 'note', text: 'Memory is scoped per-user and per-project. Secrets and credentials are blocked at the save boundary — they can never land in memory.' },
    ],
  },
  {
    id: 'concepts.tasks-journal',
    title: 'Tasks and journal',
    audience: ['both'],
    surfaces: ['web', 'ext', 'ide'],
    order: 30,
    section: 'concepts',
    body: [
      { type: 'paragraph', text: 'Three things that sound similar and are not: memory, tasks, and journal. Here is when to use which.' },
      { type: 'list', ordered: false, items: [
        'Memory — persistent facts. Preferences, decisions, patterns. Asked about repeatedly, rarely created manually.',
        'Tasks — things to do. Action items with due dates and status. You tick them off when done.',
        'Journal — reflection. Daily log, dual entries (yours and Ava observations about the session). Useful for mood tracking, session reviews, context for tomorrow.',
      ]},
      { type: 'paragraph', text: 'Ava writes to all three when it makes sense. You can write to any of them directly from the dashboard. Nothing is locked to a surface — tasks created in the CLI appear in the IDE.' },
    ],
  },
  {
    id: 'concepts.permissions',
    title: 'Permissions — three modes, ten categories',
    audience: ['both'],
    surfaces: ['web', 'ext', 'ide'],
    order: 40,
    section: 'concepts',
    body: [
      { type: 'paragraph', text: 'Ava has 60 tools. Every tool belongs to a category (file operations, shell, git, web, media, database, system, documents, memory, learning). Every tool call passes through the permission gate before it executes. You control what gets auto-approved, what asks once, and what always asks.' },
      { type: 'facts', kind: 'permissions' },
      { type: 'paragraph', text: 'Balanced is the default. Strict for when you are auditing her behaviour. Autonomous for when you want her to just go.' },
      { type: 'callout', variant: 'warning', text: 'Autonomous does not mean unchecked. Plans, clarifying questions, and explicit ask-user prompts still pause for your input. Irreversible operations (git force-push, database drops) always confirm regardless of mode.' },
    ],
  },
  {
    id: 'concepts.interjection',
    title: 'Interjection and hard-stop',
    audience: ['both'],
    surfaces: ['web', 'ext', 'ide'],
    order: 50,
    section: 'concepts',
    body: [
      { type: 'paragraph', text: 'Ava runs until her plan completes or you stop her. You have two ways to intervene while she is running.' },
      { type: 'heading', level: 3, text: 'Interject — steer without cancelling' },
      { type: 'paragraph', text: 'Type a new message while Ava is working. She finishes her current tool call, reads your message, and adjusts her plan. No context is lost. Use this when you want to redirect, add information, or change priorities mid-run.' },
      { type: 'heading', level: 3, text: 'Hard-stop — cancel and clear' },
      { type: 'paragraph', text: 'Press Escape (CLI), click Stop (extension, IDE), or type a stop command. The current run cancels, pending tool calls drop, and the conversation is ready for a fresh turn.' },
      { type: 'callout', variant: 'tip', text: 'Interject first. Hard-stop is for when something is genuinely wrong. Interjecting keeps the thread alive.' },
    ],
  },

  // ── Desktop Automation concept pages ────────────────────────────────────

  {
    id: 'concepts.desktop-personas',
    title: 'Desktop personas',
    audience: ['power'],
    surfaces: ['web', 'ext', 'ide'],
    order: 200,
    section: 'concepts',
    body: [
      { type: 'callout', variant: 'note', text: 'Available in the Ava Supernova IDE only. The VS Code extension and CLI/companion don\'t ship desktop-automation tools — open the IDE to use this feature.' },
      { type: 'paragraph', text: 'Every step in a desktop trajectory runs a five-persona wave. Each persona has one job and only one job. The separation keeps prompts tight, outputs structured, and reasoning skeptical by design.' },
      { type: 'heading', level: 3, text: 'Scout' },
      { type: 'paragraph', text: 'Reports what is visible on screen right now. Never invents elements. Never plans. Returns a ScreenState JSON with element IDs, names, bboxes, confidence, and a grounding source (UIA, Playwright DOM, or OmniParser vision).' },
      { type: 'heading', level: 3, text: 'Planner' },
      { type: 'paragraph', text: 'Decides the single next action. One action per step — never batches. Prefers reversible paths. Classifies risk per the safety ontology. Outputs a ProposedAction JSON with kind, target, params, riskClass, reasoning, and an expectedPostState prediction.' },
      { type: 'heading', level: 3, text: 'Actor' },
      { type: 'paragraph', text: 'Executes exactly what Planner proposed — after the approval gate has cleared. No improvisation. No retry. Failure is reported faithfully and Verifier handles the next move.' },
      { type: 'heading', level: 3, text: 'Verifier' },
      { type: 'paragraph', text: 'Checks whether the action landed. Compares the fresh ScreenState against Planner\'s prediction. Returns verified, deviated, or rollback_needed. Also runs loop detection — repeating an action that already succeeded is a deviation, not a verification.' },
      { type: 'heading', level: 3, text: 'Narrator' },
      { type: 'paragraph', text: 'The only voice the user hears during a trajectory. One past-tense sentence per step ("Opened Gmail.", "Clicked Compose."). Also writes the structured audit log. Says when something went wrong — never hides a problem.' },
    ],
  },

  {
    id: 'concepts.desktop-safety',
    title: 'Desktop safety ontology',
    audience: ['power'],
    surfaces: ['web', 'ext', 'ide'],
    order: 210,
    section: 'concepts',
    body: [
      { type: 'callout', variant: 'note', text: 'Available in the Ava Supernova IDE only — describes the safety model that gates every desktop automation action before Actor runs.' },
      { type: 'paragraph', text: 'Every proposed action is classified into one of five risk classes. The classification combines three signals — target metadata, semantic caption, and action parameters — and escalates up when they disagree. False positives are a nag. False negatives are a product-ending incident.' },
      { type: 'heading', level: 3, text: 'The five classes' },
      { type: 'list', ordered: false, items: [
        'Observational — read UIA tree, screenshot, hover. Always auto-allowed.',
        'Navigational — scroll, move focus, open a menu. Auto-allowed in Drive mode.',
        'Mutative-reversible — type into a field, paste, open an app, navigate a URL. Confirms in Ask mode; auto in Drive within the whitelist.',
        'Mutative-irreversible — send, submit, pay, delete, confirm, publish. Always confirms, regardless of permission level. Approval never caches.',
        'Privileged — UAC elevation, sudo, registry edits, credential prompts. Forbidden by default. Single-use opt-in required per session.',
      ]},
      { type: 'heading', level: 3, text: 'Never-cached approvals' },
      { type: 'paragraph', text: 'Every competitor caches approvals. That is the largest foothold for prompt injection — a compromised page trains the agent that clicks of that class are pre-approved. Ava never caches. Each mutative-irreversible action asks fresh.' },
      { type: 'heading', level: 3, text: 'Secrets handling' },
      { type: 'paragraph', text: 'Passwords, API keys, and 2FA codes are handled via opaque handles. Ava sees "{secret}", not the value. Never in memory, trajectory log, or prompt context — the Rust input layer substitutes the real value at keypress time.' },
    ],
  },

  {
    id: 'concepts.desktop-grounding',
    title: 'Desktop grounding hierarchy (Preview)',
    audience: ['power'],
    surfaces: ['web', 'ide'],
    order: 220,
    section: 'concepts',
    body: [
      { type: 'callout', variant: 'warning', text: 'Preview — how Scout decides which grounding source to use each step.' },
      { type: 'paragraph', text: 'Three tiers, evaluated in order. Cheapest reliable source wins.' },
      { type: 'heading', level: 3, text: '1. Browser window → Playwright DOM' },
      { type: 'paragraph', text: 'If the active window is a browser, Ava drives a dedicated headed Chromium via Playwright. DOM queries beat pixel guessing by about 10× in reliability — stable selectors, accurate wait states, precise clicks. Not a fallback; the primary path for all web.' },
      { type: 'heading', level: 3, text: '2. Native app with UIA → Windows UI Automation' },
      { type: 'paragraph', text: 'For native apps on Windows, Scout reads the UIA tree directly — control types, accessible names, bounding rectangles. If UIA returns at least five interactable elements with non-empty names, that tier wins.' },
      { type: 'heading', level: 3, text: '3. UIA empty or junk → OmniParser vision' },
      { type: 'paragraph', text: 'When UIA fails (Electron apps with poor accessibility, canvas rendering, games, remote desktop), Ava sends a redacted screenshot to OmniParser v2 — YOLOv8 detects interactable regions, Florence-2 captions each. Returns structured element tuples we can combine with any sparse UIA data.' },
      { type: 'callout', variant: 'note', text: 'OmniParser is opt-in the first time Ava needs it, with a clear privacy prompt. BYOK users can point at their own local OmniParser deployment.' },
    ],
  },

  {
    id: 'concepts.desktop-kill-switches',
    title: 'Desktop kill switches (Preview)',
    audience: ['both'],
    surfaces: ['web', 'ide'],
    order: 230,
    section: 'concepts',
    body: [
      { type: 'callout', variant: 'warning', text: 'Preview — three independent ways to abort a running trajectory. Any one of them wins.' },
      { type: 'paragraph', text: 'After reading every public autonomy incident (agents that ignored stop commands, deleted email archives, wiped drives), we built three kill switches in three different layers. None of them depend on the LLM — if Ava is wedged, you can still stop her.' },
      { type: 'heading', level: 3, text: 'Pause — space or the Pause button' },
      { type: 'paragraph', text: 'Freezes on the next step boundary. Resumable. Use this when you want to intervene without losing the trajectory.' },
      { type: 'heading', level: 3, text: 'Stop — Escape or the Stop button' },
      { type: 'paragraph', text: 'Clean abort. Narrator summarises what was done so far. Not resumable. Audit log commits.' },
      { type: 'heading', level: 3, text: 'Panic kill — triple-Escape or Ctrl+Shift+K' },
      { type: 'paragraph', text: 'Process-level abort. Rust sidecar force-quits the subprocess. Does not depend on the LLM responding, the webview being alive, or the trajectory being in a recoverable state. This is the one for when something is genuinely wrong.' },
      { type: 'paragraph', text: 'All three work from the companion app too. Either driver can end it.' },
    ],
  },
];
