import type { DocPage } from '../types.js';

// Section 2 — Core concepts. Useful to everyone.

export const CONCEPT_PAGES: DocPage[] = [
  {
    id: 'concepts.modes',
    title: 'The six modes',
    audience: ['both'],
    surfaces: ['web', 'ext', 'ide'],
    order: 10,
    section: 'concepts',
    body: [
      { type: 'paragraph', text: 'Modes change how Ava thinks, not what she can do. The same agent, the same memory, but a different mindset and a different team of specialists behind her. Type a two-character prefix to switch, or pick from the mode selector.' },
      { type: 'facts', kind: 'modes' },
      { type: 'heading', level: 3, text: 'When to use which' },
      { type: 'list', ordered: false, items: [
        'Work (>>) — you know what you want and you want it built. Full tool access. For complex multi-file work the persona team runs automatically.',
        'Plan (::) — you want a considered approach before any code changes. Read-only. You get a plan you can approve, edit, or discard.',
        'Chat (..) — you want to talk. About life, about an idea, about nothing in particular. She has memory, news, weather, and journal — and no personas.',
        'Teach (??) — you want to learn. Curriculum, lessons, quizzes, spaced repetition. Free on every plan forever.',
        'Security (!!) — you want the whole project audited. Five specialists systematically check OWASP categories and CVEs, then produce a severity-sorted report.',
        'Brainstorm (**) — you want ideas. Grounded in your context, challenged before they leave the room, refined into next steps.',
      ]},
      { type: 'callout', variant: 'tip', text: 'You can switch modes mid-conversation. Memory carries across. The specialists do not.' },
    ],
  },
  {
    id: 'concepts.memory',
    title: 'Memory — how Ava remembers you',
    audience: ['both'],
    surfaces: ['web', 'ext', 'ide'],
    order: 20,
    section: 'concepts',
    body: [
      { type: 'paragraph', text: 'Ava has a persistent memory that survives across conversations, across projects, and across machines if you enable sync. It is not a chat log. It is a structured, searchable understanding of who you are, what you like, and what you have decided.' },
      { type: 'heading', level: 3, text: 'Five layers' },
      { type: 'list', ordered: true, items: [
        'Extract — key facts captured from every message in real time.',
        'Reflect — deeper analysis runs at the end of meaningful sessions. Patterns, themes, contradictions.',
        'Accumulate — corrections and preferences compound over weeks and months.',
        'Analyse — the graph engine links related memories and flags contradictions when new information conflicts with old.',
        'Consolidate — similar memories merge; stale ones prune. Memory gets sharper over time, not noisier.',
      ]},
      { type: 'heading', level: 3, text: 'Recall' },
      { type: 'paragraph', text: 'When you ask a question, Ava searches memory by meaning (semantic search), not keywords. Mode-specific filters run alongside — Chat mode pulls personal context, Work mode pulls project decisions and code patterns.' },
      { type: 'callout', variant: 'note', text: 'Memory is scoped per-user and per-project. Secrets and credentials are blocked at the save boundary — they can never land in memory.' },
    ],
  },
  {
    id: 'concepts.tasks-journal',
    title: 'Tasks and journal',
    audience: ['both'],
    surfaces: ['web', 'ext', 'ide'],
    order: 30,
    section: 'concepts',
    body: [
      { type: 'paragraph', text: 'Three things that sound similar and are not: memory, tasks, and journal. Here is when to use which.' },
      { type: 'list', ordered: false, items: [
        'Memory — persistent facts. Preferences, decisions, patterns. Asked about repeatedly, rarely created manually.',
        'Tasks — things to do. Action items with due dates and status. You tick them off when done.',
        'Journal — reflection. Daily log, dual entries (yours and Ava observations about the session). Useful for mood tracking, session reviews, context for tomorrow.',
      ]},
      { type: 'paragraph', text: 'Ava writes to all three when it makes sense. You can write to any of them directly from the dashboard. Nothing is locked to a surface — tasks created in the CLI appear in the IDE.' },
    ],
  },
  {
    id: 'concepts.permissions',
    title: 'Permissions — three modes, ten categories',
    audience: ['both'],
    surfaces: ['web', 'ext', 'ide'],
    order: 40,
    section: 'concepts',
    body: [
      { type: 'paragraph', text: 'Ava has 61 tools. Every tool belongs to a category (file operations, shell, git, web, media, database, system, documents, memory, learning). Every tool call passes through the permission gate before it executes. You control what gets auto-approved, what asks once, and what always asks.' },
      { type: 'facts', kind: 'permissions' },
      { type: 'paragraph', text: 'Balanced is the default. Strict for when you are auditing her behaviour. Autonomous for when you want her to just go.' },
      { type: 'callout', variant: 'warning', text: 'Autonomous does not mean unchecked. Plans, clarifying questions, and explicit ask-user prompts still pause for your input. Irreversible operations (git force-push, database drops) always confirm regardless of mode.' },
    ],
  },
  {
    id: 'concepts.interjection',
    title: 'Interjection and hard-stop',
    audience: ['both'],
    surfaces: ['web', 'ext', 'ide'],
    order: 50,
    section: 'concepts',
    body: [
      { type: 'paragraph', text: 'Ava runs until her plan completes or you stop her. You have two ways to intervene while she is running.' },
      { type: 'heading', level: 3, text: 'Interject — steer without cancelling' },
      { type: 'paragraph', text: 'Type a new message while Ava is working. She finishes her current tool call, reads your message, and adjusts her plan. No context is lost. Use this when you want to redirect, add information, or change priorities mid-run.' },
      { type: 'heading', level: 3, text: 'Hard-stop — cancel and clear' },
      { type: 'paragraph', text: 'Press Escape (CLI), click Stop (extension, IDE), or type a stop command. The current run cancels, pending tool calls drop, and the conversation is ready for a fresh turn.' },
      { type: 'callout', variant: 'tip', text: 'Interject first. Hard-stop is for when something is genuinely wrong. Interjecting keeps the thread alive.' },
    ],
  },

  // ── Desktop Automation (Preview) concept pages ──────────────────────────

  {
    id: 'concepts.desktop-personas',
    title: 'Desktop personas (Preview)',
    audience: ['power'],
    surfaces: ['web', 'ide'],
    order: 200,
    section: 'concepts',
    body: [
      { type: 'callout', variant: 'warning', text: 'Preview documentation for the upcoming Desktop Automation mode. Not available in shipped releases yet.' },
      { type: 'paragraph', text: 'Every step in a desktop trajectory runs a five-persona wave. Each persona has one job and only one job. The separation keeps prompts tight, outputs structured, and reasoning skeptical by design.' },
      { type: 'heading', level: 3, text: 'Scout' },
      { type: 'paragraph', text: 'Reports what is visible on screen right now. Never invents elements. Never plans. Returns a ScreenState JSON with element IDs, names, bboxes, confidence, and a grounding source (UIA, Playwright DOM, or OmniParser vision).' },
      { type: 'heading', level: 3, text: 'Planner' },
      { type: 'paragraph', text: 'Decides the single next action. One action per step — never batches. Prefers reversible paths. Classifies risk per the safety ontology. Outputs a ProposedAction JSON with kind, target, params, riskClass, reasoning, and an expectedPostState prediction.' },
      { type: 'heading', level: 3, text: 'Actor' },
      { type: 'paragraph', text: 'Executes exactly what Planner proposed — after the approval gate has cleared. No improvisation. No retry. Failure is reported faithfully and Verifier handles the next move.' },
      { type: 'heading', level: 3, text: 'Verifier' },
      { type: 'paragraph', text: 'Checks whether the action landed. Compares the fresh ScreenState against Planner\'s prediction. Returns verified, deviated, or rollback_needed. Also runs loop detection — repeating an action that already succeeded is a deviation, not a verification.' },
      { type: 'heading', level: 3, text: 'Narrator' },
      { type: 'paragraph', text: 'The only voice the user hears during a trajectory. One past-tense sentence per step ("Opened Gmail.", "Clicked Compose."). Also writes the structured audit log. Says when something went wrong — never hides a problem.' },
    ],
  },

  {
    id: 'concepts.desktop-safety',
    title: 'Desktop safety ontology (Preview)',
    audience: ['power'],
    surfaces: ['web', 'ide'],
    order: 210,
    section: 'concepts',
    body: [
      { type: 'callout', variant: 'warning', text: 'Preview — describes the safety model that gates every desktop automation action before Actor runs.' },
      { type: 'paragraph', text: 'Every proposed action is classified into one of five risk classes. The classification combines three signals — target metadata, semantic caption, and action parameters — and escalates up when they disagree. False positives are a nag. False negatives are a product-ending incident.' },
      { type: 'heading', level: 3, text: 'The five classes' },
      { type: 'list', ordered: false, items: [
        'Observational — read UIA tree, screenshot, hover. Always auto-allowed.',
        'Navigational — scroll, move focus, open a menu. Auto-allowed in Drive mode.',
        'Mutative-reversible — type into a field, paste, open an app, navigate a URL. Confirms in Ask mode; auto in Drive within the whitelist.',
        'Mutative-irreversible — send, submit, pay, delete, confirm, publish. Always confirms, regardless of permission level. Approval never caches.',
        'Privileged — UAC elevation, sudo, registry edits, credential prompts. Forbidden by default. Single-use opt-in required per session.',
      ]},
      { type: 'heading', level: 3, text: 'Never-cached approvals' },
      { type: 'paragraph', text: 'Every competitor caches approvals. That is the largest foothold for prompt injection — a compromised page trains the agent that clicks of that class are pre-approved. Ava never caches. Each mutative-irreversible action asks fresh.' },
      { type: 'heading', level: 3, text: 'Secrets handling' },
      { type: 'paragraph', text: 'Passwords, API keys, and 2FA codes are handled via opaque handles. Ava sees "{secret}", not the value. Never in memory, trajectory log, or prompt context — the Rust input layer substitutes the real value at keypress time.' },
    ],
  },

  {
    id: 'concepts.desktop-grounding',
    title: 'Desktop grounding hierarchy (Preview)',
    audience: ['power'],
    surfaces: ['web', 'ide'],
    order: 220,
    section: 'concepts',
    body: [
      { type: 'callout', variant: 'warning', text: 'Preview — how Scout decides which grounding source to use each step.' },
      { type: 'paragraph', text: 'Three tiers, evaluated in order. Cheapest reliable source wins.' },
      { type: 'heading', level: 3, text: '1. Browser window → Playwright DOM' },
      { type: 'paragraph', text: 'If the active window is a browser, Ava drives a dedicated headed Chromium via Playwright. DOM queries beat pixel guessing by about 10× in reliability — stable selectors, accurate wait states, precise clicks. Not a fallback; the primary path for all web.' },
      { type: 'heading', level: 3, text: '2. Native app with UIA → Windows UI Automation' },
      { type: 'paragraph', text: 'For native apps on Windows, Scout reads the UIA tree directly — control types, accessible names, bounding rectangles. If UIA returns at least five interactable elements with non-empty names, that tier wins.' },
      { type: 'heading', level: 3, text: '3. UIA empty or junk → OmniParser vision' },
      { type: 'paragraph', text: 'When UIA fails (Electron apps with poor accessibility, canvas rendering, games, remote desktop), Ava sends a redacted screenshot to OmniParser v2 — YOLOv8 detects interactable regions, Florence-2 captions each. Returns structured element tuples we can combine with any sparse UIA data.' },
      { type: 'callout', variant: 'note', text: 'OmniParser is opt-in the first time Ava needs it, with a clear privacy prompt. BYOK users can point at their own local OmniParser deployment.' },
    ],
  },

  {
    id: 'concepts.desktop-kill-switches',
    title: 'Desktop kill switches (Preview)',
    audience: ['both'],
    surfaces: ['web', 'ide'],
    order: 230,
    section: 'concepts',
    body: [
      { type: 'callout', variant: 'warning', text: 'Preview — three independent ways to abort a running trajectory. Any one of them wins.' },
      { type: 'paragraph', text: 'After reading every public autonomy incident (agents that ignored stop commands, deleted email archives, wiped drives), we built three kill switches in three different layers. None of them depend on the LLM — if Ava is wedged, you can still stop her.' },
      { type: 'heading', level: 3, text: 'Pause — space or the Pause button' },
      { type: 'paragraph', text: 'Freezes on the next step boundary. Resumable. Use this when you want to intervene without losing the trajectory.' },
      { type: 'heading', level: 3, text: 'Stop — Escape or the Stop button' },
      { type: 'paragraph', text: 'Clean abort. Narrator summarises what was done so far. Not resumable. Audit log commits.' },
      { type: 'heading', level: 3, text: 'Panic kill — triple-Escape or Ctrl+Shift+K' },
      { type: 'paragraph', text: 'Process-level abort. Rust sidecar force-quits the subprocess. Does not depend on the LLM responding, the webview being alive, or the trajectory being in a recoverable state. This is the one for when something is genuinely wrong.' },
      { type: 'paragraph', text: 'All three work from the companion app too. Either driver can end it.' },
    ],
  },
];
