import type { DocPage } from '../types.js';

// Section 3 — Reference. Power-user material. Hidden by the Beginner/Everything toggle.

export const REFERENCE_PAGES: DocPage[] = [
  {
    id: 'reference.tools',
    title: 'Tool reference',
    audience: ['power'],
    surfaces: ['web', 'ext', 'ide'],
    order: 10,
    section: 'reference',
    body: [
      { type: 'paragraph', text: 'The full built-in toolbox. Every tool here is registered in the core runtime and available to Ava when the mode and permission mode allow it. Filter by category or risk.' },
      { type: 'facts', kind: 'tools' },
      { type: 'heading', level: 3, text: 'Risk levels' },
      { type: 'list', ordered: false, items: [
        'Safe — reads state without modifying anything. file_read, glob, grep, git_status.',
        'Write — modifies files, creates commits, produces artefacts. file_edit, git_commit, generate_image.',
        'Dangerous — runs shell, controls the desktop, hits the network, queries databases. bash, browser, computer_use.',
      ]},
      { type: 'callout', variant: 'note', text: 'Persona specialists have their own tool allowlists. Scout can read but not write. Builder has full access. Challenger has no tools at all — its job is to question the plan.' },
    ],
  },
  {
    id: 'reference.providers',
    title: 'Provider and model matrix',
    audience: ['power'],
    surfaces: ['web', 'ext', 'ide'],
    order: 20,
    section: 'reference',
    body: [
      { type: 'paragraph', text: 'Seven providers. Two classes: platform-managed (we handle the keys, you use your token allowance) and BYOK (you bring your own API key, your requests never touch our platform).' },
      { type: 'heading', level: 3, text: 'Platform-managed' },
      { type: 'paragraph', text: 'Available on every plan, including the free tier. Tokens count against your plan allowance. Managed keys are rotated and monitored by the platform — nothing for you to configure.' },
      { type: 'facts', kind: 'providers', filter: { kind: 'managed' } },
      { type: 'heading', level: 3, text: 'Bring your own key' },
      { type: 'paragraph', text: 'Paste your API key in settings. BYOK requests go direct from Ava to the provider — they do not pass through our infrastructure and do not consume platform tokens. You pay the provider; we do not see the traffic.' },
      { type: 'facts', kind: 'providers', filter: { kind: 'byok' } },
      { type: 'callout', variant: 'note', text: 'Pricing shown is our best read of the provider rate card at publication. Always check the provider website before committing to a workload.' },
    ],
  },
  {
    id: 'reference.personas',
    title: 'Persona orchestration',
    audience: ['power'],
    surfaces: ['web', 'ext', 'ide'],
    order: 30,
    section: 'reference',
    body: [
      { type: 'paragraph', text: '24 specialists across 5 mode teams. The Conductor decides which team runs, in what order, and with what context. Chat mode has no personas — it is Ava herself.' },
      { type: 'heading', level: 3, text: 'How orchestration runs' },
      { type: 'list', ordered: true, items: [
        'You send a message in Plan, Teach, Security, or Brainstorm mode (or a complex Work request).',
        'The Conductor reads the request, picks the mode team, and builds an execution plan — some personas run sequentially, some in parallel waves.',
        'Each persona has its own system prompt, a restricted tool allowlist, and a shared context pool of what previous personas found.',
        'The final persona produces a summary, a plan, or a report, depending on mode.',
        'Ava presents the result to you. You approve, tweak, or redirect.',
      ]},
      { type: 'facts', kind: 'personas' },
      { type: 'callout', variant: 'tip', text: 'Work mode only invokes the full team for complex tasks. Simple edits run Ava directly — no orchestration overhead.' },
    ],
  },
  {
    id: 'reference.cli',
    title: 'CLI commands',
    audience: ['power'],
    surfaces: ['web', 'ext', 'ide'],
    order: 40,
    section: 'reference',
    body: [
      { type: 'paragraph', text: 'The CLI is a REPL. These slash commands work from the prompt.' },
      { type: 'list', ordered: false, items: [
        '/help — list commands and current mode.',
        '/mode <name> — switch mode (work, plan, chat, teach, security, brainstorm).',
        '/model <id> — switch model without leaving the session.',
        '/clear — clear the current conversation. Memory is untouched.',
        '/history — list past conversations in this project.',
        '/memory — open the memory browser.',
        '/tasks — list and manage tasks.',
        '/journal — open today journal entry.',
        '/settings — open the settings menu.',
        '/exit — quit the REPL.',
      ]},
      { type: 'heading', level: 3, text: 'Launch flags' },
      { type: 'list', ordered: false, items: [
        '--mode <name> — start in a specific mode.',
        '--model <id> — start with a specific model.',
        '--permission <mode> — strict / balanced / autonomous.',
        '--project <path> — set the project root explicitly.',
      ]},
    ],
  },
  {
    id: 'reference.config',
    title: 'Configuration',
    audience: ['power'],
    surfaces: ['web', 'ext', 'ide'],
    order: 50,
    section: 'reference',
    body: [
      { type: 'paragraph', text: 'Ava reads configuration from two scopes. Global settings live in ~/.ava/. Project settings live in .ava/ at the project root.' },
      { type: 'heading', level: 3, text: 'Global — ~/.ava/' },
      { type: 'list', ordered: false, items: [
        'settings.json — model preferences, permission mode, personality, language.',
        'memory/ — your global memories (preferences, decisions that apply everywhere).',
        'tasks.json — cross-project task list.',
        'journal/ — daily journal entries, date-organised.',
      ]},
      { type: 'heading', level: 3, text: 'Project — .ava/' },
      { type: 'list', ordered: false, items: [
        'instructions.md — project-specific instructions Ava always loads. Durable context ("we use pnpm, not npm", "API keys live in 1Password").',
        'context.md — optional freeform project notes.',
        'memory/ — memories scoped to this project.',
        'datasets/config.json — opt-in dataset capture configuration.',
      ]},
      { type: 'callout', variant: 'tip', text: 'Add .ava/ to .gitignore if you do not want to share memories with your team. Keep instructions.md in the repo — that is how Ava learns the project conventions.' },
    ],
  },
  {
    id: 'reference.shortcuts',
    title: 'Keyboard shortcuts',
    audience: ['power'],
    surfaces: ['web', 'ext', 'ide'],
    order: 60,
    section: 'reference',
    body: [
      { type: 'paragraph', text: 'Shortcuts by surface. Customise them in each surface settings.' },
      { type: 'facts', kind: 'shortcuts' },
    ],
  },
  {
    id: 'reference.project-context',
    title: 'Project context',
    audience: ['power'],
    surfaces: ['web', 'ext', 'ide'],
    order: 70,
    section: 'reference',
    body: [
      { type: 'paragraph', text: 'Ava loads several layers of context when you open a project. Understanding the layers helps you put information in the right place.' },
      { type: 'heading', level: 3, text: 'Loaded automatically' },
      { type: 'list', ordered: false, items: [
        '.ava/instructions.md — treated as durable, high-priority guidance. Always in context.',
        '.ava/context.md — freeform notes. Loaded, lower priority.',
        'README.md — scanned on first run for project summary.',
        'package.json / pyproject.toml / Cargo.toml — read to detect language, framework, test command.',
        '.gitignore — respected by all file tools (glob, grep, project_index).',
      ]},
      { type: 'heading', level: 3, text: 'Loaded on demand' },
      { type: 'list', ordered: false, items: [
        'Project index — a structured map of files, symbols, and imports. Built lazily when Ava needs it.',
        'Git history — pulled when git_status, git_diff, or git_create_pr are called.',
        'Memory — semantically matched entries are injected per turn, not all at once.',
      ]},
      { type: 'callout', variant: 'tip', text: 'Put conventions in instructions.md. Put notes in context.md. Let memory capture the rest on its own.' },
    ],
  },
];
