/**
 * Report Generator — Combines data sources into structured reports.
 *
 * Pulls from tasks, journal, memory, and git to produce
 * weekly status reports, project health checks, sprint reviews, etc.
 * This is the JARVIS moment — "Ava, prep my board brief."
 */

import { writeFile, mkdir } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import type { Tool, ToolResult, ToolExecutionContext, ToolRiskLevel } from './types.js';
import type { FunctionSchema } from '../providers/types.js';
import type { TaskManager } from '../tasks/task-manager.js';
import type { JournalManager } from '../journal/journal-manager.js';
import type { MemoryManager } from '../memory/memory-manager.js';

export class ReportGenerateTool implements Tool {
  readonly name = 'report_generate';
  readonly description = 'Generate a structured report from tasks, journal, memory, and project data.';
  readonly riskLevel: ToolRiskLevel = 'write';
  readonly requiresConfirmation = true;

  readonly schema: FunctionSchema = {
    name: 'report_generate',
    description: 'Generate a structured report by combining data from tasks, journal entries, memories, and project context. Supports multiple report types: weekly status, project health, sprint review, board brief.',
    parameters: {
      type: 'object',
      properties: {
        report_type: {
          type: 'string',
          enum: ['weekly-status', 'project-health', 'sprint-review', 'board-brief', 'custom'],
          description: 'Type of report to generate',
        },
        title: { type: 'string', description: 'Report title (auto-generated if omitted)' },
        file_path: { type: 'string', description: 'Output file path (e.g. "reports/weekly-2026-03-17.md")' },
        period_days: { type: 'number', description: 'Number of days to cover (default: 7)' },
        include_tasks: { type: 'boolean', description: 'Include task summary (default: true)' },
        include_journal: { type: 'boolean', description: 'Include journal highlights (default: true)' },
        include_decisions: { type: 'boolean', description: 'Include key decisions from memory (default: true)' },
        custom_sections: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              heading: { type: 'string' },
              content: { type: 'string' },
            },
            required: ['heading', 'content'],
          },
          description: 'Additional custom sections to include',
        },
      },
      required: ['report_type', 'file_path'],
    },
  };

  async execute(args: Record<string, unknown>, context: ToolExecutionContext): Promise<ToolResult> {
    const reportType = args.report_type as string;
    const filePath = args.file_path as string;
    const periodDays = (args.period_days as number) || 7;
    const includeTasks = args.include_tasks !== false;
    const includeJournal = args.include_journal !== false;
    const includeDecisions = args.include_decisions !== false;
    const customSections = args.custom_sections as Array<{ heading: string; content: string }> | undefined;

    if (!filePath || !reportType) {
      return { success: false, output: 'report_type and file_path are required.' };
    }

    const absolutePath = filePath.startsWith('/') || filePath.includes(':')
      ? filePath
      : join(context.cwd, filePath);

    const now = new Date();
    const periodStart = new Date(now);
    periodStart.setDate(periodStart.getDate() - periodDays);
    const startDate = periodStart.toISOString().slice(0, 10);
    const endDate = now.toISOString().slice(0, 10);

    const title = (args.title as string) || this.defaultTitle(reportType, endDate);

    // Build report sections
    const sections: string[] = [];
    sections.push(`# ${title}`);
    sections.push(`\n*Generated by Ava | Supernova on ${endDate}*`);
    sections.push(`*Period: ${startDate} — ${endDate}*\n`);

    // Task summary
    if (includeTasks && context.sharedState?.taskManager) {
      const taskSection = await this.buildTaskSection(
        context.sharedState.taskManager as TaskManager,
        startDate,
      );
      if (taskSection) sections.push(taskSection);
    }

    // Journal highlights
    if (includeJournal && context.sharedState?.journalManager) {
      const journalSection = await this.buildJournalSection(
        context.sharedState.journalManager as JournalManager,
        startDate,
        endDate,
      );
      if (journalSection) sections.push(journalSection);
    }

    // Key decisions from memory
    if (includeDecisions && context.sharedState?.memoryManager) {
      const decisionSection = await this.buildDecisionSection(
        context.sharedState.memoryManager as MemoryManager,
      );
      if (decisionSection) sections.push(decisionSection);
    }

    // Custom sections
    if (customSections && customSections.length > 0) {
      for (const section of customSections) {
        sections.push(`## ${section.heading}\n\n${section.content}`);
      }
    }

    const content = sections.join('\n\n---\n\n');

    try {
      await mkdir(dirname(absolutePath), { recursive: true });
      await writeFile(absolutePath, content, 'utf-8');

      return {
        success: true,
        output: `Report generated: ${absolutePath}\n\n${content}`,
        metadata: {
          path: absolutePath,
          reportType,
          periodDays,
          lineCount: content.split('\n').length,
        },
      };
    } catch (err) {
      return { success: false, output: `Failed to write report: ${err}` };
    }
  }

  private defaultTitle(reportType: string, date: string): string {
    switch (reportType) {
      case 'weekly-status': return `Weekly Status Report — ${date}`;
      case 'project-health': return `Project Health Check — ${date}`;
      case 'sprint-review': return `Sprint Review — ${date}`;
      case 'board-brief': return `Board Brief — ${date}`;
      default: return `Report — ${date}`;
    }
  }

  private async buildTaskSection(taskManager: TaskManager, since: string): Promise<string | null> {
    try {
      const allTasks = await taskManager.listTasks({ includeArchived: true });

      const completed = allTasks.filter(t =>
        t.completedAt && t.completedAt >= since
      );
      const inProgress = allTasks.filter(t => t.status === 'in-progress');
      const overdue = allTasks.filter(t =>
        t.dueDate && t.dueDate < new Date().toISOString().slice(0, 10) &&
        t.status !== 'done' && t.status !== 'archived'
      );

      const lines: string[] = ['## Tasks'];

      if (completed.length > 0) {
        lines.push(`\n**Completed (${completed.length}):**`);
        for (const t of completed.slice(0, 10)) {
          lines.push(`- ✓ ${t.title}`);
        }
      }

      if (inProgress.length > 0) {
        lines.push(`\n**In Progress (${inProgress.length}):**`);
        for (const t of inProgress.slice(0, 10)) {
          lines.push(`- → ${t.title}`);
        }
      }

      if (overdue.length > 0) {
        lines.push(`\n**Overdue (${overdue.length}):**`);
        for (const t of overdue.slice(0, 5)) {
          lines.push(`- ⚠ ${t.title} (due ${t.dueDate})`);
        }
      }

      if (completed.length === 0 && inProgress.length === 0) return null;

      return lines.join('\n');
    } catch {
      return null;
    }
  }

  private async buildJournalSection(journalManager: JournalManager, from: string, to: string): Promise<string | null> {
    try {
      const days = await journalManager.getDaysInRange(from, to);
      if (days.length === 0) return null;

      const lines: string[] = ['## Journal Highlights'];

      for (const day of days.slice(-5)) {
        const entry = day.userEntry ?? day.avaEntry;
        if (!entry) continue;
        const firstLine = entry.content.split('\n')[0].slice(0, 120);
        lines.push(`\n**${day.date}:** ${firstLine}`);
      }

      return lines.join('\n');
    } catch {
      return null;
    }
  }

  private async buildDecisionSection(memoryManager: MemoryManager): Promise<string | null> {
    try {
      const store = await memoryManager.loadProjectStore();
      if (!store) return null;

      const decisions = store.entries
        .filter(e => e.category === 'decision' && !e.archived)
        .sort((a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime())
        .slice(0, 5);

      if (decisions.length === 0) return null;

      const lines: string[] = ['## Key Decisions'];
      for (const d of decisions) {
        const content = d.content.split('\n')[0].slice(0, 150);
        lines.push(`\n- ${content}`);
      }

      return lines.join('\n');
    } catch {
      return null;
    }
  }
}
